name: 'Release plugin'
inputs:
  plugin-path:
    description: 'Path of the plugin to release'
    required: true

runs:
  using: "composite"

  steps:
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Generate types
      run: yarn tsc

    - name: Build
      run: yarn build

    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@1.3.8
      with:
        workspace: ${{ inputs.plugin-path }}
        tag_name: "v%s"
        tag_message: "v%s"
        commit_pattern: "^Release (\\S+)"
      env: # More info about the environment variables in the README
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
